### ISSUE TITLE
让ps和Process Browser 同时存在并生效

### ISSUE THREAD

**Issue by 0x3rhy** [H4de5-7/geacon_pro#1]
## 那么能否让这两者并存呢? 当然可以, 解决方法如下
![image](https://user-images.githubusercontent.com/69976059/198514134-2e549c2a-1e4d-457b-b62c-7ba62048fc39.png)
![image](https://user-images.githubusercontent.com/69976059/198514289-377afb1a-3e49-4591-bc12-a8c532b0b06e.png)
---
## 我打印出cmdBuf相关信息, 发现使用进程浏览器的时候cmdbuf最后多了一个标志位, 那么代码就好写了, 判断一下选择 callbackType类型, ps命令最好用CALLBACK_PROCESS_LIST也就是17更好兼容,  ListProcess函数最好还是像你兄弟那样写, 需要sessionId
![image](https://user-images.githubusercontent.com/69976059/198515002-3cf88bf2-ed43-4658-bf08-c0931d2c20dd.png)
## 最后效果命令ps和进程浏览器都能使用了
![image](https://user-images.githubusercontent.com/69976059/198515162-a24b7f46-6ba1-40c5-8503-831b4d805853.png)
![image](https://user-images.githubusercontent.com/69976059/198515260-c035e0ff-e697-4105-b307-9308354b2843.png)

**Comment by H4de5-7** [comment]
谢谢师傅的指出！已修改！
