### ISSUE TITLE
编译后的beacon大小5.6M？

### ISSUE THREAD

**Issue by ybdt** [H4de5-7/geacon_pro#10]
正常编译后就是大小5.6M吗？用来钓鱼的话，稍微有点大
![image](https://user-images.githubusercontent.com/65813455/200163969-4f1dd848-2a99-4cbb-a571-36f7857fa775.png)

**Comment by H4de5-7** [comment]
网上也有一些其他的缩小体积的方法，师傅可以去搜搜，体积大算是go的弊端吧。。我们在开发的时候尽可能地去减小体积了，后续也会再看看能不能继续减小。不过个人感觉现实中捆绑pptx这些文件5M也还好，word的话多放几张图感觉也还行，lnk和捆绑钓鱼感觉体积也还好，师傅也可以看看我另外一个项目免杀捆绑器。如果觉得接受不了的话可以尝试用我的另一个powershell免杀项目来远程下载并加载geacon_pro。

**Comment by H4de5-7** [comment]
如果师傅有需要的话我可以尝试改一个只有上传下载功能的geacon_pro，然后用小马来下载大马。

**Comment by ybdt** [comment]
非常感谢师傅的回答，我试下免杀捆绑项目以及powershell免杀远程加载：）

**Comment by ybdt** [comment]
顺便想问下，公钥和私钥是对应的哪个文件啊~

**Comment by H4de5-7** [comment]
这部分与geacon项目是一致的，师傅可以看一下原项目https://github.com/darkr4y/geacon

**Comment by ybdt** [comment]
编译beacontool提取了公钥私钥，最后编译了geacon_pro，经测试可以过defender、卡巴免费版、火绒、腾讯，但是360会拦截
![image](https://user-images.githubusercontent.com/65813455/200179691-108d94b7-6eb0-4527-bdd4-9ef971e26193.png)

**Comment by H4de5-7** [comment]
欸，不会啊，我这两天还当着360上线呢，有可能是做了啥操作hash被标记了？师傅换一个路径去编译，或者加点无用的代码，或者用garble这个项目混淆一下呢？

**Comment by H4de5-7** [comment]
师傅方便加一个好友吗，看看是啥情况，主页有qq

**Comment by ybdt** [comment]
好的师傅，加您了

**Comment by ybdt** [comment]
第2天早测试，同样的beacon二开文件，同样的测试环境，360又不杀了，可能触发了360的“乱杀功能”吧
