### ISSUE TITLE
请问下支持域前置的CS吗

### ISSUE THREAD

**Issue by 8irdy** [H4de5-7/geacon_pro#11]
我自己试了下域前置的CS，好像上不了线，可能是弟弟太菜了

**Comment by Z3ratu1** [comment]
域前置时CDN应该是通过host处的域名进行转发的，host直接指定cdn ip并在config里面的header加一项对应域名的host即可

**Comment by H4de5-7** [comment]
经过师傅的测试是支持域前置的，我已经更新在README里面了

**Comment by 8irdy** [comment]
感谢，已解决
