### ISSUE TITLE
不会配置

### ISSUE THREAD

**Issue by craw11** [H4de5-7/geacon_pro#15]
能简单说一下配置方法吗

**Comment by H4de5-7** [comment]
基本的配置步骤在中文的使用说明里写了，师傅具体是哪方面的配置疑问呀。

**Comment by craw11** [comment]
> 

谢谢师傅的回复,就是我在config.go里配置了我的c2监听器地址,cmd显示success,但是cs上并没有显示主机
![d29d91d82304b38fd26ad15af36aaf1](https://user-images.githubusercontent.com/68812236/202413709-33d1878b-5228-4cd3-a8ae-eeb525dc322a.jpg)
![421e2c6759a0d5904496b8bd58aa69f](https://user-images.githubusercontent.com/68812236/202413772-124de0a4-6152-4a8e-bcce-67331d83e294.jpg)

**Comment by craw11** [comment]
> > 
> 
> 谢谢师傅的回复,就是我在config.go里配置了我的c2监听器地址,cmd显示success,但是cs上并没有显示主机 ![d29d91d82304b38fd26ad15af36aaf1](https://user-images.githubusercontent.com/68812236/202413709-33d1878b-5228-4cd3-a8ae-eeb525dc322a.jpg) ![421e2c6759a0d5904496b8bd58aa69f](https://user-images.githubusercontent.com/68812236/202413772-124de0a4-6152-4a8e-bcce-67331d83e294.jpg)



> 基本的配置步骤在中文的使用说明里写了，师傅具体是哪方面的配置疑问呀。

是还有其他需要配置的地方吗

**Comment by H4de5-7** [comment]
listener是http嘛，http的话需要把config里面的sslHTTP改成plainHTTP

**Comment by craw11** [comment]
> listener是http嘛，http的话需要把config里的sslHTTP改成plainHTTP

这个我已经修改了,还是跟之前一样的情况

**Comment by H4de5-7** [comment]
公钥修改了吗，firstblood没有显示的话应该是公钥出错了。

**Comment by H4de5-7** [comment]
公钥和geacon这个项目是一样的，用一个java tool来提取，具体的用法可以移步geacon这个项目（其实在说明文档里面也写了

**Comment by craw11** [comment]
> 公钥和geacon这个项目是一样的，用一个java工具来提取，具体的使用方法可以移步geacon这个项目（其实际上在说明文档里面也写了

![image](https://user-images.githubusercontent.com/68812236/202422378-6b857212-3310-4956-a574-3a6ede01ec36.png)
我现在修改成这样还是cs上没有出现上线的主机

**Comment by H4de5-7** [comment]
师傅的cs是什么版本呀

**Comment by craw11** [comment]
> 师傅的cs是什么版本呀

4.4

**Comment by H4de5-7** [comment]
可以看一下服务端的报错吗

**Comment by craw11** [comment]
> 师傅的cs是什么版本呀

我明天换个版本的cs试一下

> 可以看一下服务端的报错吗

![image](https://user-images.githubusercontent.com/68812236/202423034-0d900790-5ef7-46b5-baaf-035d1a51c877.png)

**Comment by H4de5-7** [comment]
C2profile也是说明里面给的示例嘛

**Comment by craw11** [comment]
> C2profile也是说明里面给的示例嘛

没有找到C2profile在哪啊

**Comment by H4de5-7** [comment]
在说明里面有的，师傅可以看一下

**Comment by craw11** [comment]
> 在说明里面有的，师傅可以看一下

抱歉师傅我还是有些不懂,请问直接将示例代码追加到config.go里面去吗
![image](https://user-images.githubusercontent.com/68812236/202425263-69d1e937-5637-468e-8f78-e97dd564f64b.png)

**Comment by H4de5-7** [comment]
cs服务端有一个文件叫C2profile，用来设置服务端和客户端的，师傅可以搜一下具体怎么用，然后把这个示例更换成C2profile即可。

**Comment by craw11** [comment]
> cs服务端有一个文件叫C2profile，用来设置服务端和客户端的，师傅可以搜一下具体怎么用，然后把这个示例更换成C2profile即可。

ok了师傅,我已经按照你的方法配置好了,非常感谢

**Comment by H4de5-7** [comment]
好滴，后续有疑问或者想法可以随时交流

**Comment by superjock1988** [comment]
师傅能出个简单的视频吗

**Comment by H4de5-7** [comment]
更新了中文版readme，师傅们可以看看配置的过程。
