### ISSUE TITLE
this platform not supports HideConsole now.问题

### ISSUE THREAD

**Issue by lightcsec** [H4de5-7/geacon_pro#17]
师傅想问一下，不支持mac平台嘛还是我配置错了:(
<img width="462" alt="图片" src="https://user-images.githubusercontent.com/71672296/202864456-f567af4c-628a-4f5b-b627-c2c1ee1a0811.png">

**Comment by Z3ratu1** [comment]
这个是针对windows平台的选项，用来取消那个黑框的，在mac上直接后台执行就不会有一个终端的框，所以mac下不支持，在config.go里面把HideConsole那个选项关掉就可以了

**Comment by lightcsec** [comment]
嗯嗯问题解决了，但是cs服务端会存在报错，报错如下
A Malleable C2 attempt to recover data from a '.http-get.client.metadata' transaction failed. This could be due to a bug in the profile, a change made to the profile after this Beacon was run, or a change made to the transaction by some device between your target and your Cobalt Strike controller. The following information will (hopefully) help narrow down what happened.
<img width="1213" alt="图片" src="https://user-images.githubusercontent.com/71672296/202887318-69a306df-f8a9-4d15-850a-9f222b56aa43.png">

profile已经换上了并且也配置好了，不知道什么原因

**Comment by H4de5-7** [comment]
可以看一下config.go嘛，可以把关键信息部分打码。

**Comment by lightcsec** [comment]
嗯嗯没问题的
<img width="661" alt="图片" src="https://user-images.githubusercontent.com/71672296/202887409-1f6374c4-ae8e-4bbc-b09e-89eeaa8be6b4.png">
<img width="813" alt="图片" src="https://user-images.githubusercontent.com/71672296/202887436-86115d5d-b68a-4c1f-88be-d3d05ccdd64b.png">

**Comment by lightcsec** [comment]
服务端报错貌似是 http-get-metadata 出的问题，下面是我的profile的配置
<img width="721" alt="图片" src="https://user-images.githubusercontent.com/71672296/202887513-6460a41c-ea15-4302-b351-197372d39dd0.png">

**Comment by Z3ratu1** [comment]
你更新c2profile的同时需要在config.go中同步更新对应字段，可以先试一下项目中给出的c2profile和默认config

**Comment by lightcsec** [comment]
师傅可以加个联系方式嘛？还是有点问题Orz

**Comment by H4de5-7** [comment]
联系方式在我的主页，base64解一下qq就可以。

**Comment by lightcsec** [comment]
好的已添加
