### ISSUE TITLE
请问适配Cs4.4版本吗？

### ISSUE THREAD

**Issue by badboycxcc** [H4de5-7/geacon_pro#2]
请问适配Cs4.4版本吗？是否有过测试，效果如何？

**Comment by H4de5-7** [comment]
理论上应该是适配的，项目刚做出来没有太多测试，不好意思，我一会儿测试一下

**Comment by badboycxcc** [comment]
ok

**Comment by 0xa-saline** [comment]
> 请问适配Cs4.4版本吗？是否有过测试，效果如何？

目前测试4.7 大部分功能正常。

**Comment by Z3ratu1** [comment]
如果不考虑高版本下提供的新功能的话，不同版本间的适配只需要改metadata部分就可以了，也就是说如果能正常上线则基本功能均可使用。

**Comment by H4de5-7** [comment]
> <img alt="image" width="1213" src="https://user-images.githubusercontent.com/59011386/198874341-9f8909e8-ebd8-4b5d-8e88-9743256b90b2.png">
> 
> mac 上线进程

是最新版本的代码嘛

**Comment by H4de5-7** [comment]
> 

![a443ba392a0f92b070ccee55424a8d7](https://user-images.githubusercontent.com/48757788/198875704-126f28c0-cba8-43ea-a040-3a62a243ab46.jpg)
我这边是没问题的呀，按理说linux可以mac也可以，你ps命令是正常的吗

**Comment by H4de5-7** [comment]
> > > 
> > 
> > 
> > ![a443ba392a0f92b070ccee55424a8d7](https://user-images.githubusercontent.com/48757788/198875704-126f28c0-cba8-43ea-a040-3a62a243ab46.jpg) 我这边mac是没问题的呀，你ps命令是正常的吗
> 
> 有没有可能我是M1的mac

可能架构不一样？你把go的env换成arm编译呢？我这边使用amd64编译的

**Comment by badboycxcc** [comment]
> <img alt="image" width="1213" src="https://user-images.githubusercontent.com/59011386/198874341-9f8909e8-ebd8-4b5d-8e88-9743256b90b2.png">
> 
> mac 上线进程

我M1芯片也是这样。

**Comment by H4de5-7** [comment]
> > <img alt="image" width="1213" src="https://user-images.githubusercontent.com/59011386/198874341-9f8909e8-ebd8-4b5d-8e88-9743256b90b2.png">
> > mac 上线进程
> 
> 我M1芯片也是这样。

应该是arm的问题，我这两天看一下。

**Comment by H4de5-7** [comment]
> > <img alt="image" width="1213" src="https://user-images.githubusercontent.com/59011386/198874341-9f8909e8-ebd8-4b5d-8e88-9743256b90b2.png">
> > mac 上线进程
> 
> 我M1芯片也是这样。

师傅可以下一下最新的代码吗？新版的应该可以正常显示了，请注意新版示例的C2profile有更改
