### ISSUE TITLE
上线报错

### ISSUE THREAD

**Issue by beenjoke** [H4de5-7/geacon_pro#22]
服务端提示:
rejected client from XX.XX.XX.XX: invalid auth protocol (old client?)

config.go中目前就添加了公钥 ，请问C2参数配置的是服务端地址吗？
config.go中也没看到c2profile中对应需要修改的配置

**Comment by Z3ratu1** [comment]
c2profile使用项目提供的默认profile即可，这个报错感觉很像是你用的server是魔改版，把beacon的magic number改了导致的验证失败

**Comment by beenjoke** [comment]
> 是的，是服务器listener的地址，师傅是不是弄成了服务器认证的地址。

修改成监听器地址后 ，报Dropped HTTP client from /XX.XX.XX.XX (malformed header)

**Comment by Z3ratu1** [comment]
malformed header需要确认c2profile配置，如果未对config.go中的内容请使用项目提供的模板profile

**Comment by H4de5-7** [comment]
> > 是的，是服务器listener的地址，师傅是不是弄成了服务器认证的地址。
> 
> 修改成监听器地址后 ，报Dropped HTTP client from /XX.XX.XX.XX (malformed header)

或者有可能是http和https协议对不上？config.go里面是https但是listener是http的？

**Comment by beenjoke** [comment]
> 

我这儿c2profile是按readme给的直接用，config.go 也是直接拿来用的，所以是c2profile要按照config.go来改，还是config.go要按照c2profile来改呢？

**Comment by beenjoke** [comment]
> > > 
> > 
> > 
> > 我这儿c2profile是按readme给的直接用，config.go 也是直接拿来用的，所以是c2profile要按照config.go来改，还是config.go要按照c2profile来改呢？
> 
> config.go根据c2profile来改，师傅这个问题解决了吗，如果listener是http的但是config.go里面的是https协议可能会报错，我怀疑是这个问题。

From   'XX.XX.XX.XX'
URI    '/www/handle/doc'

Headers
-------
'Cookie' = 'SESSIONID='
'REMOTE_ADDRESS' = '/XX.XX.XX.XX'
'Server' = 'nginx/1.10.3 (Ubuntu)'
'User-Agent' = 'Go-http-client/1.1'
'Connection' = 'close'
'Host' = 'XX.XX.XX.XX:7777'
'Pragma' = 'public'
'Accept-Encoding' = 'gzip'
'Cache-Control' = 'must-revalidate, post-check=0, pre-check=0'
'Vary' = 'Accept'
'Expires' = '0'
'Content-Type' = 'application/octet-stream'

[-] Invalid session id
[-] A Malleable C2 attempt to recover data from a '.http-get.client.metadata' transaction failed. This could be due to a bug in the profile, a change made to the profile after this Beacon was run, or a change made to the transaction by some device between your target and your Cobalt Strike controller. The following information will (hopefully) help narrow down what happened.

1.config我已全部使用http
2.config.go完全按照给的c2profile来改，报上面错误，麻了。。。

**Comment by H4de5-7** [comment]
感觉像公钥的问题，session为空，师傅方便加下好友嘛，具体调试一下

**Comment by H4de5-7** [comment]
问题已解决，配置公钥时需要按照Begin和End的格式。
