### ISSUE TITLE
Invalid session id

### ISSUE THREAD

**Issue by GG-o1** [H4de5-7/geacon_pro#23]
元数据加密出来是空的，MakeMetaInfo()是有数据的：
<img width="855" alt="image" src="https://user-images.githubusercontent.com/32947015/207840158-8c413d22-2f5e-429b-96a4-43723b487d63.png">
然后服务端这边就接收不到SESSIONID
<img width="784" alt="image" src="https://user-images.githubusercontent.com/32947015/207840202-85ea4206-a9ef-4636-9334-a0ce22fadff9.png">
公私钥已更改：
<img width="698" alt="image" src="https://user-images.githubusercontent.com/32947015/207840739-098d37b9-98aa-49e8-bfa0-5fdbda1491a4.png">

**Comment by H4de5-7** [comment]
师傅的公钥和私钥是不是反了？

**Comment by GG-o1** [comment]
反了，我的问题
