### ISSUE TITLE
云函数上线报错

### ISSUE THREAD

**Issue by wangfly-me** [H4de5-7/geacon_pro#27]
CS4.7使用自己的profile，报错DEBUG: ciphertext is not a multiple of the block size
![Screenshot 2022-12-26 002750](https://user-images.githubusercontent.com/25388540/209475471-7f5f7b65-19ac-42d8-9482-690787078124.png)

**Comment by wangfly-me** [comment]
无论什么操作，都会报这个错。

**Comment by H4de5-7** [comment]
在设置append这些的时候是不是没有加/r换行符？我们计划之后会简化自己配置config.go的过程。

**Comment by wangfly-me** [comment]
我试试

**Comment by wangfly-me** [comment]
在config.go里面加嘛

**Comment by H4de5-7** [comment]
师傅修改c2profile后需要在config.go对应的位置同样修改一下的。之前有师傅遇到过类似的问题，是因为换成自己的profile文件后，多行append配置在config.go中没有加/
换行符。
