### ISSUE TITLE
main.exe 在 windows 7 x86 系统上运行不了

### ISSUE THREAD

**Issue by Shulelk** [H4de5-7/geacon_pro#29]

**Comment by H4de5-7** [comment]
师傅编译的时候把GOARCH换成了x86了嘛

**Comment by Shulelk** [comment]
感谢师傅提醒。修改过后能够运行，且与 CS 服务器  Listen 的 IP:PORT 建立了连接，但是在 CS 客户端中没有显示上线的受害机一栏

**Comment by H4de5-7** [comment]
有具体的截图嘛，因为我们对x86系统并没有完备的测试，可能会有一些bug。

**Comment by Shulelk** [comment]
客户端应该是没有问题的，我的 C2 配置能够在 Win 10 上线且服务端没有报错，但是在这台 Win 7 上服务端却报错了
![12](https://user-images.githubusercontent.com/121603500/209925002-b38a4c93-1364-4bf2-b2db-563c3f18db24.png)

**Comment by H4de5-7** [comment]
我手上目前没有x86的机子，刚刚在win10上执行了x86的exe是可以正常上线的，师傅这里的internal address像是内网地址获取错误？test是哪个字段呀？师傅可以尝试在GetLocalIPInt这个函数里面调试一下输出，可能是把内网字段获取成其他的字段了？

**Comment by H4de5-7** [comment]
x64的没问题吧？感觉是meta信息的问题，我们看一看。

**Comment by Shulelk** [comment]
C2 的 meta 部分是师傅提供的默认的，C2 文件也只是注释掉 post-ex 的末尾三行，尝试了 x64 Win 7 的内网机子也不行。

**Comment by H4de5-7** [comment]
内网的ipconfig方便发一下嘛，可以隐掉敏感的内容，想看一下输出。

**Comment by Shulelk** [comment]
![ipconfig1](https://user-images.githubusercontent.com/121603500/209934919-675ea8d3-d225-4316-86f0-84d5971057fa.png)

![ipconfig2](https://user-images.githubusercontent.com/121603500/209935021-ebf33c2d-5c2a-401a-b4ee-5e90e27370db.png)

**Comment by H4de5-7** [comment]
好奇怪。。之前也没有遇到过这种情况，我们再想想可能是啥问题。

**Comment by Z3ratu1** [comment]
我这边32位木马能够在64位的win7和win server2008上运行，无32位机器无法本地复现。师傅给出的报错很奇怪，因为CS4.1+版本内网IP地址应当是一个4个8位无符号整数，报错应该不会出现将`Administrator`这么长的字符串作为IP去判断，但是CS4.0版本的metadata中内网IP是通过字符串传递的，请确认一下CS的版本师傅是4.1+（但这win10能上线就又说不通了）
若版本仍无问题则请将packet.go第223行的`metaInfo`变量输出，我肉眼观察一下问题

**Comment by Shulelk** [comment]
噢噢。CS 版本是 4.0 的，不向下兼容吗？

**Comment by H4de5-7** [comment]
geacon_pro只支持4.1+的，4.0可以移步到geacon_plus
