### ISSUE TITLE
config.go根据c2profile修改

### ISSUE THREAD

**Issue by Gexiaolungg** [H4de5-7/geacon_pro#30]
师傅您好，您的readme中说明了根据c2profile对应修改config.go，不知您是否方便指点一下具体修改哪些地方

**Comment by H4de5-7** [comment]
如果快速使用的话可以直接使用示例的c2profile（其实示例c2profile流量侧已经配置了不少东西了）不需要修改config.go。如果自己配置可以根据config.go中具体的字段名称来对应，比如说Http_post_id_crypt=[]string{"mask", "netbiosu"}对应着c2profile中的http-post中的id里面的mask;和netbiosu;。我们下个阶段主要的任务是简化配置的过程。

**Comment by Gexiaolungg** [comment]
> 

十分感谢您的指导

**Comment by H4de5-7** [comment]
莫事应该的，后续有问题可以随时交流。
