### ISSUE TITLE
大文件下载错误

### ISSUE THREAD

**Issue by 1203731177** [H4de5-7/geacon_pro#31]
当下载1m以上文件时，文件上传到c2服务器错误。可能原因是文件已发送，但服务器只接受1m以下的post包，所以认为是错误，因而重新启动下载任务，循环往复。

**Comment by H4de5-7** [comment]
不应该啊，我们之前测试的时候几百M的也没有问题，师傅用的是最新版本的吗，有报错截图吗，我明天测试一下。

**Comment by 1203731177** [comment]
![图片](https://user-images.githubusercontent.com/41557960/211616216-2408b088-97f5-486f-9e0c-25d10f1b1369.png)
![图片](https://user-images.githubusercontent.com/41557960/211616286-d847bff2-0e4e-4247-a9e6-479e83e33b23.png)
文件原始大小8m，cs版本4.5。

**Comment by 1203731177** [comment]
这么晚还不睡，辛苦师傅了

**Comment by H4de5-7** [comment]
师傅用其他的机子试一下呢？这是真实的机子？会不会是环境的问题。

**Comment by 1203731177** [comment]
真机，我也很奇怪，网络都是畅通的，http包也有回复，但是就是报错然后重复发送post包。
![图片](https://user-images.githubusercontent.com/41557960/211617572-c478946f-b22a-42be-b997-23720b2d9d05.png)
设计是直接发送文件还是分片发送呢。

**Comment by 1203731177** [comment]
我的推测只能是cs服务器软件问题。

**Comment by H4de5-7** [comment]
每次发1M，我们也上锁了，很怪。

**Comment by 1203731177** [comment]
![图片](https://user-images.githubusercontent.com/41557960/211618296-3b39bf21-8b45-4645-9f61-e8f9c9771aca.png)

**Comment by 1203731177** [comment]
你也出问题了？

**Comment by H4de5-7** [comment]
我明天测试下，有点怪，这个问题按理说之前解决了。

**Comment by 1203731177** [comment]
好的，辛苦啦[ღ( ´･ᴗ･` )比心]

**Comment by H4de5-7** [comment]
应该的hhh

**Comment by 1203731177** [comment]
对不起，师傅，昨天没有计算发送的大小，看起来确实分成1m左右的片。通过测试发现，实际网络环境对比较大的包传输较慢引起timeout，进而触发重复发包，已经通过设置timeout解决。
很精密的软件，感谢师傅的百忙之中抽空解疑。

**Comment by H4de5-7** [comment]
是设置的哪里的timeout呢？

**Comment by 1203731177** [comment]
config.go文件里有timeout选项

**Comment by H4de5-7** [comment]
好的师傅，后续我们会再测试测试。

**Comment by H4de5-7** [comment]
okk好滴
