### ISSUE TITLE
config.go需要怎么修改呢师傅

### ISSUE THREAD

**Issue by guanglianniubi** [H4de5-7/geacon_pro#32]

**Comment by H4de5-7** [comment]
具体的配置可参考readme、issue#30和issue#15，后续我们会尽快更新自动化配置。

**Comment by guanglianniubi** [comment]
![图片](https://user-images.githubusercontent.com/45590232/213065201-08e041c9-b746-42ce-a370-d2f29cf98e8a.png)

**Comment by H4de5-7** [comment]
是不是listener是http类型但是config.go里面是https头？

**Comment by guanglianniubi** [comment]
是的 我没注意到这点 感谢

**Comment by H4de5-7** [comment]
莫事应该的。
