### ISSUE TITLE
Need normal guide

### ISSUE THREAD

**Issue by useragent23253** [H4de5-7/geacon_pro#33]
Hello. Can anybody to write normal guide to setup this project from compilation to set up profiles etc

**Comment by H4de5-7** [comment]
You can translate README_zh.md to find more details. README_zh.md has more detailed content than README.md. Sorry for our oversight, we will update the README.md as soon as possible.

**Comment by useragent23253** [comment]
Bro, how correct compile on *nix like systems? I've got some errors

-[~/Desktop/Github/geacon
└─$ mvn compile
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.043 s
[INFO] Finished at: 2023-01-26T01:12:04-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/host/Desktop/Github/geacon). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by Z3ratu1** [comment]
what are you compiling? geacon_pro is writen in golang, you need to install golang and use it to compile binary. 
you may use `go mod get; go build ./main.go` to build binary.
java files under `tools` folder is used for extract RSA public key from CS server, and have nothing to do with geacon's build

**Comment by Z3ratu1** [comment]
I use IDEA to build that jar, so I don't know how to build it under cmdline.
if you don't mind, there is a copy that I have compiled
https://drive.google.com/file/d/1OOB3xt2Rafd0GThojhJvAPG9J4jiBPWJ/view?usp=sharing

**Comment by useragent23253** [comment]
thank you brother

**Comment by H4de5-7** [comment]
Hi, I have updated README.md.
