### ISSUE TITLE
（待确认？）特定情况下无法通过 Windows Defenter 静态检测？

### ISSUE THREAD

**Issue by badboycxcc** [H4de5-7/geacon_pro#4]
<img width="477" alt="截屏2022-10-29 下午7 12 54" src="https://user-images.githubusercontent.com/72059221/198828255-e3e0d610-f47c-4c2c-9d12-90601c7d83de.png">

**Comment by H4de5-7** [comment]
不会呀，开发的时候我都是开着defender和360的，卡巴也试过。
![1667043510183](https://user-images.githubusercontent.com/48757788/198829337-948320dd-c6e5-4f7a-a438-b5931b095270.png)
![1667043600726](https://user-images.githubusercontent.com/48757788/198829392-b5a6a1e5-b3c7-4507-b905-47e97dfa5ab8.png)
你是直接下下来编译的嘛。

**Comment by badboycxcc** [comment]
是的，我是Linux跨平台编译的，代码没做改动。

**Comment by badboycxcc** [comment]
编译方法
<img width="777" alt="截屏2022-10-29 下午7 57 09" src="https://user-images.githubusercontent.com/72059221/198830116-946d152e-2eee-4518-81d5-1d5db1bc648d.png">

**Comment by H4de5-7** [comment]
我这边也在kali编译的，没问题呀，可以正常上线，你把publickey换成自己的，然后配上C2profile看看能不能上线
![1667045136340](https://user-images.githubusercontent.com/48757788/198830498-8a298fae-17e8-4796-bc87-e736d199fe31.png)
![1667045174010](https://user-images.githubusercontent.com/48757788/198830499-7ac8a63e-03d2-4f18-bc5f-5d40167f008c.png)

**Comment by badboycxcc** [comment]
我在Mac上本地编译后测试上线没问题，能执行命令，不过我是使用公网VPS部署的。
Windows信息：
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22000 暂缺 Build 22000
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free

**Comment by H4de5-7** [comment]
我平时测试也在公网测试的，和在不在公网应该没关系，win11我也在朋友的电脑上测试过了。。你要不尝试变动一下代码，有没有可能执行过很敏感的操作所以这个hash被标记过了？你这种情况我之前没有遇到过。。要不你直接mac编译呢

**Comment by badboycxcc** [comment]
嗯，我这边继续测试一下。

**Comment by H4de5-7** [comment]
麻烦了

**Comment by badboycxcc** [comment]
刚刚在Mac编译没有被杀，很奇怪。不过测试screenshot会导致程序崩溃退出。

**Comment by H4de5-7** [comment]
我觉得应该不是啥大问题，我之前测试的时候都是没问题的，我基本都是在windows编译环境下测试的，有可能编译不一样？建议在windows下编译，我这边screentshot是没有问题的。

**Comment by badboycxcc** [comment]
ok，我在windows编译看看。
