### ISSUE TITLE
最新版在Windows server2008上会闪退

### ISSUE THREAD

**Issue by D2550** [H4de5-7/geacon_pro#41]
cs会有上线提示，然就就没有后续了，查看Windows发现也没进程了，同样的文件在Windows11一切正常。编译命令
```
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build main.go  
 go version
go version go1.19.5 linux/amd64
```
搭建过程：https://blog.njcit.me/2023/02/06/%E5%86%85%E7%BD%91/geacon-pro%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/

**Comment by D2550** [comment]
猜测原因：  
在Windows11下面会自动最小化到任务栏，在Windows2008下面最小化之后就消失了，大概和这个有关系？

**Comment by H4de5-7** [comment]
昨天晚上测试的时候发现unhook的实现不是很稳定，然后我们换了种实现的方式但对部分版本依旧无法支持。目前把unhook设置成可选项了，师傅可以下载下昨天晚上更新的代码，readme里面也做了说明。我们后续会看看有没有好的解决办法。

**Comment by D2550** [comment]
感谢
