### ISSUE TITLE
使用私有证书无法上线

### ISSUE THREAD

**Issue by yukar1z0e** [H4de5-7/geacon_pro#42]
CS的证书是申请的cloudflare的证书，然后使用keytool生成了新的.store文件，然后在profile里面删除了
```
https-certificate {
    set C "KZ";
    set CN "foren.zik";
    set O "NN Fern Sub";
    set OU "NN Fern";
    set ST "KZ";
    set validity "365";
}
```
新增了
```
https-certificate {
	set keystore "new.store";
	set password "password";
}
```
然后生成的木马无法上线

**Comment by H4de5-7** [comment]
服务端报错的信息可以看一下嘛。

**Comment by yukar1z0e** [comment]
服务端没有响应也没有报错，客户端运行的时候直接爆了`public key error`
<img width="291" alt="1" src="https://user-images.githubusercontent.com/44317939/217757168-6ce5141e-c85a-47d3-ac79-216608f9f8b5.png">

**Comment by H4de5-7** [comment]
哦哦哦这个因为config.go里面公钥设置错误，begin public key那一行需要无缩进，方便的话师傅可以发一下config.go上半段的图片。

**Comment by yukar1z0e** [comment]
哦哦，尴尬了。
我一开始以为的无缩进的意思是要把begin public key + 证书 + end写在一行里。
上线了。
