### ISSUE TITLE
终端提示DEBUG: This type is not supported now.

### ISSUE THREAD

**Issue by x-Ai** [H4de5-7/geacon_pro#44]
- 操作系统：Windows 11 22H2
- Cobalt Strike版本：4.7
- Profile：jquery-c2.4.7.profile

#### <p align="center">上线无问题，命令执行无问题，功能正常，终端提示DEBUG: This type is not supported now</p>
****
#### 根据cobaltstrike.jar中beacon/BeaconData及beacon/BeaconC2来看，从元数据中获取到的任务输出类型都为"6"，暂不清楚到底问题在哪里。
![image](https://user-images.githubusercontent.com/5061489/221385719-f36a5c9f-ecf8-4636-9374-2dad12305ebf.png)

![image](https://user-images.githubusercontent.com/5061489/221385733-d03bd55f-aecf-4001-ac02-7d527f6e0abf.png)

![image](https://user-images.githubusercontent.com/5061489/221387103-62a29472-095f-467a-ab9d-3ce12d1c9afb.png)

#### 运行后打印的结果：
![image](https://user-images.githubusercontent.com/5061489/221379499-eb7cd5e7-91be-4252-9b71-1511bd304b44.png)

**Comment by Z3ratu1** [comment]
证明6这个命令号对应的功能并未实现，我们还没有在win11上进行过测试，但是从上线的情况来看metadata有所缺失，可能win11的版本号信息影响了metadata的布局？
（感觉上有点像被识别成了类似dns beacon的东西?可能这个命令和dns  beacon有关？师傅能帮忙看一眼6对应的命令是啥吗）

**Comment by H4de5-7** [comment]
应该是c2profile里面有data_jitter的设置，目前暂时不支持，readme里面有标注，师傅可以试一下，我们后续会改进。

**Comment by x-Ai** [comment]
> 应该是c2profile里面有data_jitter的设置，目前暂时不支持，readme里面有标注，师傅可以试一下，我们后续会改进。

#### 感谢帮助，的确为data_jitter设置问题。
