### ISSUE TITLE
好像已经过不了WD静态检测了

### ISSUE THREAD

**Issue by bytecaps** [H4de5-7/geacon_pro#46]
默认编译 `go build ` 落地就嘎

![image](https://user-images.githubusercontent.com/52679771/223302645-5104b2bd-7aea-4316-a5c6-5511dd3a76b8.png)

**Comment by H4de5-7** [comment]
我试试

**Comment by bytecaps** [comment]
> 我试试

用linux交叉编译了一下 好像能过静态了

**Comment by bytecaps** [comment]
windows还是不行 落地就杀  ，linux 也不能使用 `-s -w`

**Comment by H4de5-7** [comment]
我刚刚下载了一份最近版本的代码然后在win11的defender上面测了一下，静态和动态都没有问题，师傅可以尝试换个路径编译一下。有的时候测试多了defender会乱查杀。。目前看国内杀软应该还是没啥问题的，国外的部分杀软可能需要用garble混淆一下。

**Comment by bytecaps** [comment]
> 我刚刚下载了一份最新版本的代码然后在win11的defender上面测了一下，静态和动态都没有问题，师傅可以尝试换个路径编译一下。有的时候测试多了defender会乱查杀。。目前看国内杀软应该还是没啥问题的，国外的部分杀软可能需要用garble混淆一下。

我本地没有开defender，我是本地(windows 11)生成，去服务器(windows 2016)上测试，落地就杀(病毒库是最新)，朋友(windows 10)哪也是落地就杀，目前我自己改了一点代码，已经过静态了，谢谢师傅。

**Comment by H4de5-7** [comment]
我怀疑是你本地编译信息的问题，我这边没有问题hhh你换台机子编译估计就好了

**Comment by H4de5-7** [comment]
我也是本地编译然后去朋友的机子测试的。

**Comment by bytecaps** [comment]
> 我也是本地编译然后去朋友的机子测试的。

ok，谢谢师傅
