### ISSUE TITLE
交叉编译 Windows x86 报错

### ISSUE THREAD

**Issue by badboycxcc** [H4de5-7/geacon_pro#48]
<img width="1502" alt="截屏2023-03-09 下午4 57 12" src="https://user-images.githubusercontent.com/72059221/223971416-69b1da6b-917f-4a35-960f-960ec333c794.png">

**Comment by H4de5-7** [comment]
这是因为调用的直接系统调用的库暂时未支持x86，我更新了一版，把x86和x64分开编译了。
