### ISSUE TITLE
net share 会退出进程

### ISSUE THREAD

**Issue by badboycxcc** [H4de5-7/geacon_pro#5]
执行 net share 会造成程序崩溃退出。

**Comment by H4de5-7** [comment]
部分net指令还没有测试，是只有net share会崩溃还是其他的也会？我明天看一下

**Comment by badboycxcc** [comment]
beacon> shell start /b D:\mail.exe
mail.exe 能正常启动，但是自身退出啦。

**Comment by H4de5-7** [comment]
> beacon> shell start /b D:\mail.exe
> mail.exe 能正常启动，但是自身退出啦。

执行exe建议用run，shell的实现调用了go本身的库而不是createprocess，可能有区别，我一会儿试试

**Comment by badboycxcc** [comment]
> > beacon> shell start /b D:\mail.exe
> > mail.exe 能正常启动，但是自身退出啦。
> 
> 执行exe建议用run，shell的实现调用了go本身的库而不是createprocess，可能有区别，我一会儿试试

ok，CobaltStrike run指令会让程序后台运行吗？

**Comment by H4de5-7** [comment]
> 

我设置了隐藏窗口，你可以试一下

**Comment by H4de5-7** [comment]
> 执行 net share 会造成程序崩溃退出。

已将shell的实现更改为CreateProcess，现在应该不会出现net share崩溃的情况，不过执行隐藏窗口不建议使用start /b，直接shell或者run就可以了
