### ISSUE TITLE
shell执行成功但无响应（CS 4.5）

### ISSUE THREAD

**Issue by peterzh4ng** [H4de5-7/geacon_pro#6]
CS 版本：4.5 带xss修复
攻击机环境：Win10，java 8
靶机环境：Win10

靶机能够上线，发送`shell whoami`之后，在靶机本地确定了命令执行成功，但cs没有打印结果。
可能的原因1：包发过去但被cs拒绝了，因为PushResult的时候，HttpPost方法里发请求的时候没带id信息（我的profile配置的`header "Cookie";`）。

**Comment by H4de5-7** [comment]
师傅修改了config.go里面的header设置嘛，config.go里面的设置是我提供的示例profile文件，如果要自己修改的话需要同时修改config.go

**Comment by peterzh4ng** [comment]
刚刚测试了一下，是因为我的profile配置的post包的id需要prepend，并且是放在header的Cookie中的。
但根据您代码里的内容发现，post的id字段是写死在post请求的url的Cookie参数中（看起来很不合理哈）的，应该属于程序的扩展性问题，可以改进，但不算bug。

**Comment by peterzh4ng** [comment]
> 师傅修改了config.go里面的header设置嘛，config.go里面的设置是我提供的示例profile文件，如果要自己修改的话需要同时修改config.go

config.go根据profile配置过了。

**Comment by H4de5-7** [comment]
> 刚刚测试了一下，是因为我的profile配置的post包的id需要prepend，并且是放在header的Cookie中的。 但根据您代码里的内容发现，post的id字段是写死在post请求的url的Cookie参数中（看起来很不合理哈）的，应该属于程序的扩展性问题，可以改进，但不算bug。

我的问题，目前对C2profile的适配度还不够好，我下午尝试把get和post的代码改一下

**Comment by H4de5-7** [comment]
已更新，麻烦师傅测试一下

**Comment by peterzh4ng** [comment]
> 已更新，麻烦师傅测试一下

`shell whoami` 可以正常接收到响应了！

**Comment by H4de5-7** [comment]
> > 已更新，麻烦师傅测试一下
> 
> `shell whoami` 可以正常接收到响应了！

好滴，谢谢师傅的测试，后续有任何问题或者需求的话麻烦提出来hhh
