### ISSUE TITLE
Invalid Session ID

### ISSUE THREAD

**Issue by xzajyjs** [H4de5-7/geacon_pro#7]
使用示例Profile，上线时teamserver端报错
```
[-] Dropped HTTP client from /172.16.12.2 (malformed header)
```
修改main.go中line19-20的sslHTTP为plainHTTP后报错如下：
```
[-] Invalid session id
[-] A Malleable C2 attempt to recover data from a '.http-get.client.metadata' transaction failed. This could be due to a bug in the profile, a change made to the profile after this Beacon was run, or a change made to the transaction by some device between your target and your Cobalt Strike controller. The following information will (hopefully) help narrow down what happened.

From   '172.16.12.2'
URI    '/www/handle/doc'

Headers
-------
'Cookie' = 'SESSIONID='
'REMOTE_ADDRESS' = '/172.16.12.2'
'Accept' = '*/*'
'Server' = 'nginx'
'User-Agent' = 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0; BOIE9;ENUS)'
'Connection' = 'close'
'Host' = 'aliyun.com'
'Accept-Encoding' = 'gzip'
'Content-Type' = 'text/html;charset=UTF-8'
```

**Comment by Z3ratu1** [comment]
你这里sessionID直接变成空了，只有http会出错，https不会？

**Comment by xzajyjs** [comment]
> 

选择https时服务端报错`[-] Dropped HTTP client from /172.16.12.2 (malformed header)`，客户端报错`get connect error`;
选择http时客户端不报错，显示success

**Comment by Z3ratu1** [comment]
我认为，你需要创建对应的http(s) listener来接收消息
![image](https://user-images.githubusercontent.com/49296657/199377925-557024a7-177d-4e50-b320-3d610ad9ef4b.png)

**Comment by xzajyjs** [comment]
> 我认为，你需要创建对应的http(s) listener来接收消息 ![image](https://user-images.githubusercontent.com/49296657/199377925-557024a7-177d-4e50-b320-3d610ad9ef4b.png)

起初创建的就是Beacon HTTP listener
经过尝试，在 HTTPS listener下，服务端不报错，客户端报错依旧是`get connect error`

**Comment by H4de5-7** [comment]
师傅方便加一下我的好友嘛，issue上面沟通有一点麻烦，我们可能需要师傅帮忙测试一下。qq在我的主页base64解一下

**Comment by Z3ratu1** [comment]
metadata为空可能是RSA加密的时候有几个字段太长导致的，做了个简单的长度限制

**Comment by H4de5-7** [comment]
该问题由于在rsa解密的时候未把\x00字符去除，在当前版本已进行了修正。
